#!/bin/bash
set -e

/usr/local/bin/mise trust /workspaces/python-chess/mise.toml && /usr/local/bin/mise install

apt update && apt install vim -y

if [ ! -f board.yaml ]; then
  cat > board.yaml <<EOL
fen: "startpos"
moves: []
game_over: false
winner: null
EOL
  echo "Created initial board.yaml"
else
  echo "board.yaml already exists"
fi

